# Generated by Django 2.0.1 on 2018-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktype',
            name='risk_type_name',
            field=models.CharField(error_messages={'unique': 'risk_type_name must be unique'}, max_length=100, unique=True),
        ),
    ]
